package com.moviebot.bot.enums;

public enum AdminState {
    NONE,
    AWAITING_TITLE,
    AWAITING_CODE,
    AWAITING_TYPE,
    AWAITING_DESCRIPTION,
    AWAITING_POSTER,
    AWAITING_VIDEO,
    AWAITING_SEASON_COUNT,
    AWAITING_SEASON_POSTER,
    AWAITING_EPISODE_COUNT,
    AWAITING_EPISODE_VIDEO,
    AWAITING_SEASON_POSTER_EDIT,
    AWAITING_NEW_EPISODE_VIDEO,
    AWAITING_CHANNEL_USERNAME,
    AWAITING_BROADCAST_CONTENT,
    AWAITING_BROADCAST_CONFIRM
}
