package com.moviebot.bot.enums;

public enum AdminState {
    NONE,
    AWAITING_TITLE,
    AWAITING_CODE,
    AWAITING_TYPE,
    AWAITING_DESCRIPTION,
    AWAITING_VIDEO,
    AWAITING_SEASON_COUNT,
    AWAITING_EPISODE_COUNT,
    AWAITING_EPISODE_VIDEO
}
